name = "SmoQyDEAC"
uuid = "9c442b74-637f-4296-b43a-959aa316565a"
authors = ["James Neuhaus <james.neuhaus@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
